- name: Install Kubernetes dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
    state: present

- name: Add Kubernetes GPG key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: Add Kubernetes repo
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main

- name: Install Kubernetes tools
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present